apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fakeshop
  name: fakeshop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fakeshop
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '5000'
        prometheus.io/path: '/metrics'
      labels:
        app: fakeshop
    spec:
      containers:
      - image: psmetildes/fake-shop:1.0
        name: fakeshops
        ports:
        - containerPort: 5000
        envFrom:
          - configMapRef:
              name: fakeshop-config
          - secretRef:
              name: fakeshop-secret


