apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: fakeshop
  name: fakeshop
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: fakeshop
  type: LoadBalancer
status:
  loadBalancer: {}
